version: '3.1'

services:
  redis:
    image: redis:7.0.8-alpine
    restart: always
    ports:
      - "6379:6379"
  db:
    image: postgres:14.7-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
  consul:
    image: consul:1.14.4
    restart: always
    ports:
      - "8600:8600/udp"
      - "8600:8600"
      - "8500:8500"
      - "8300:8300"
      - "8301:8301/udp"
      - "8301:8301"
      - "8302:8302/udp"
      - "8302:8302"
    volumes:
      - consul_data:/consul/data
    command: agent -bootstrap -server -ui -auto-reload-config=true -client=0.0.0.0 -data-dir=/consul/data/
  # pharmacy-user:
  #   image: pharmacy-user:0.0.1-SNAPSHOT
  #   restart: always
  #   build: .
  #   ports:
  #     - "3001:3001"
  #   environment:
  #     MIGRATE_PATH: /tmp/migrations
  #     CONSUL_SERVER_URLS: consul:8500
volumes:
  consul_data:
    external: false
  postgres_data:
    external: false